### PR TITLE
replace setContext and getContext with exported objects, to support s…

### LINKED ISSUE #11: Unhandled Promise Rejection: Error: Function called outside component initialization
I was trying a demo site and upgrade Svelte to the latest version, but after clicking to a login button I get an error 
"Unhandled Promise Rejection: Error: Function called outside component initialization"

I tried with reverting svelte version and I can see that version 3.24.1 works but it's broken on 3.25.x onwards.

Steps to reproduce
- update package.json with 3.25.0
- `npm i`
- `npm run showcase:dev`
- open browser and click login

### PR DESCRIPTION
**Pull request by koo5**
…velte 3.25
should close #11 and #10 

i'm a js newbie so i don't know how idiomatic this is, suggestions appreciated.

### CODE REVIEW

**Comment by koo5** [comment]
https://www.reddit.com/r/sveltejs/comments/krejt1/is_it_possible_to_call_setcontext_inside_onmount/

**Comment by scav** [comment]
@dopry this works for me as well, can you please consider merging this if you think this is okay?

**Comment by tomaaron** [comment]
Thank you @koo5. This works for me as well.

**Comment by dopry** [comment]
I'll try to get to it today.  I've been meaning to get around to this.

**Comment by koo5** [comment]
i guess this should properly be done with stores?

**Comment by dopry** [comment]
I'm not really comfortable abandoning the context. I updated the code to use the contexts properly instead. getContext/setContext need to be called in initialization. I added an Auth0LoginButton and Auth0LogoutButton demonstrating how to use the context and call the functions without abandoning the concept of contexts.

**Pull request closed without merging**
