### PR TITLE
Adds option for adding classes to buttons

### PR DESCRIPTION
**Pull request by scav**
As useful as these buttons are, being able to add classes to them is nice to have. Perhaps there are better ways, but I am unaware of any.

### CODE REVIEW

**Comment by dopry** [comment]
@scav this looks awesome... can you add the btn class to the showcase?  I was thinking about that when I implemented this.

**Comment by scav** [comment]
Like so?

**Comment by dopry** [comment]
Perfecto, I'll merge this tomorrow when I have a minute to test.

**Comment by dopry** [comment]
@scav Awesome work! thanks for fixing this up. Sorry it took me a minute to get around to it. I had to wrap up another project.

**Pull request merged**
